"""initial db setup

Revision ID: a4f4effdb3d8
Revises: 
Create Date: 2025-11-17 15:14:36.749165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f4effdb3d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_worked_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('intervention_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('physical_sensation', sa.String(), nullable=True),
    sa.Column('internal_narrative', sa.String(), nullable=True),
    sa.Column('emotion_label', sa.String(), nullable=True),
    sa.Column('ai_identified_pattern', sa.String(), nullable=True),
    sa.Column('technique_id', sa.String(), nullable=True),
    sa.Column('personalized_message', sa.String(), nullable=True),
    sa.Column('intervention_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('intervention_started_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_checkin_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['app.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_table('check_ins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('optional_notes', sa.String(), nullable=True),
    sa.Column('emotion_after', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['app.intervention_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_ins', schema='app')
    op.drop_table('intervention_sessions', schema='app')
    op.drop_table('tasks', schema='app')
    # ### end Alembic commands ###